#!/bin/sh

cd "$( dirname "${BASH_SOURCE[0]}" )/../.."

time tools/import/ericthesaurus ericdata/ERICthesaurus.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1965.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1966.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1967.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1968.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1969.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1970.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1971.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1972.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1973.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1974.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1975.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1976.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1977.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1978.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1979.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1980.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1981.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1982.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1983.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1984.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1985.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1986.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1987.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1988.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1989.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1990.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1991.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1992.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1993.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1994.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1995.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1996.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1997.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1998.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric1999.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric2000.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric2001.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric2002.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric2003.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric2004.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric2005.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric2006.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric2007.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric2008.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric2009.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric2010.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric2011.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric2012_01.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric2012_02.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric2012_03.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric2012_04.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric2012_05.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric2012_06.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric2012_07.xml &&
sleep 10 &&
time tools/import/eric ericdata/eric2012_08.xml &&
sleep 10 &&
time tools/import/eric ericdata/ERIC201209.xml &&
sleep 10 &&
time tools/import/eric ericdata/ERIC201210.xml &&
sleep 10 &&
time tools/import/eric ericdata/ERIC201211.xml &&
sleep 10 &&
time tools/import/eric ericdata/ERIC201212.xml &&
sleep 10 &&
time tools/import/eric ericdata/ERIC201301.xml &&
sleep 10 &&
time tools/import/eric ericdata/ERIC201302.xml &&
sleep 10 &&
time tools/import/eric ericdata/ERIC201303.xml &&
sleep 10 &&
time tools/import/eric ericdata/ERIC201304.xml &&
sleep 10 &&
time tools/import/eric ericdata/ERIC201305.xml &&
sleep 10 &&
time tools/import/eric ericdata/ERIC201306.xml &&
sleep 10 &&
time tools/import/eric ericdata/ERIC201307.xml

