#!/usr/bin/env node
// vim: set filetype=javascript:
var options = require('../src/lib/cmd')("Load records into Biblionarrator", {
        'format': {
            alias: 'f',
            describe: 'Data format to import'
        },
        'importer': {
            alias: 'i',
            describe: 'Select the importer (json or xml) to use'
        },
        'lookup': {
            alias: 'l',
            describe: 'Use a lookup table and create links retrospectively',
            boolean: true
        },
        'match': {
            alias: 'm',
            describe: 'Criterion for matching (index:field)'
        },
        'map': {
            describe: 'Remap a field using the CSV file. Specified as 500$a:file.csv'
        },
        'overlay': {
            alias: 'o',
            default: false,
            boolean: true,
            describe: 'Overlay matching records'
        },
        'skip': {
            boolean: true,
            describe: 'Skip matching records'
        },
        'reject': {
            default: 'import.rej',
            describe: 'File name in which to store rejected records'
        },
        'recordclass': {
            describe: 'Record class to use for records'
        },
        'commit': {
            default: 1000,
            describe: 'Number of records to process between commits'
        },
        'quiet': {
            alias: 'q',
            default: false,
            describe: 'Quiet mode (do not print progress)'
        }
    }),
    environment = require('../src/lib/environment'),
    JSONImporter = require('bn-importers/lib/json'),
    XMLImporter = require('bn-importers/lib/xml'),
    graphstore = environment.graphstore,
    models = require('../src/models'),
    Record = models.Record,
    util = require('util'),
    fs = require('fs'),
    Q = require('q'),
    extend = require('extend'),
    async = require('async'),
    handler = require('../src/lib/formats/' + options.format);
var inspect = require('eyes').inspector({maxLength: false});

graphstore.autocommit = false;

var importer,
    importopts = {
        files: options._,
        commit: options.commit,
        pause: (options.map ? true : false),
        quiet: options.quiet
    };
if (typeof handler.importoptions !== 'undefined') {
    importer = options.importer || handler.importoptions.importer;
    handler.importoptions[importer] = handler.importoptions[importer] || { };
    extend(true, importopts, handler.importoptions[importer]);
}
if (importer === 'xml') {
    importer = new XMLImporter(importopts);
} else if (importer === 'json') {
    importer = new JSONImporter(importopts);
}

var maps = { };

if (options.map) {
    var csv = require('csv');
    var mappromises = [ ];
    if (util.isArray(options.map)) {
        options.map.forEach(function (map) {
            var prom = Q.defer();
            addMap(map, prom);
            mappromises.push(prom.promise);
        });
    } else {
        var prom = Q.defer();
        addMap(options.map, prom);
        mappromises.push(prom.promise);
    }
    Q.all(mappromises).done(function () {
        importer.start();
    });
}

var linkcount = 0;
var linkerr = 0;
var recordcount = 0;
var mainrecordcount = 0;

var lookup = { }, linksleft = { };
var linkfuncs = [ ];

importer.on('record', function (record, mypromise) {
    mainrecordcount++;
    var rec;
    var subpromises = [ ];
    var matcher = function (matchpoint) {
        return (rec = Record.findOne(matchpoint));
    };
    record = handler.import(record, options, maps, matcher);
    if (!rec) {
        rec = new Record(record);
    } else if (options.overlay) {
        rec.format = options.format;
        rec.data = record.data;
    } else {
        mypromise.resolve();
        return;
    }
    rec.save(function (err, rec) {
        if (err) return mypromise.reject(record);
        if (typeof rec.key !== 'undefined') lookup[rec.key] = rec.id;
        var links = rec.getLinks();
        links.forEach(function (link) {
            linkfuncs.push(doLink.bind(undefined, rec, link));
        });
        if (options.lookup && typeof rec.key !== 'undefined') {
            if (linksleft[rec.key]) {
                linksleft[rec.key].forEach(function (link) {
                    var linkpromise = Q.defer();
                    subpromises.push(linkpromise.promise);
                    rec.link(link.label, link.source, link.properties, true, function (err, res) {
                        if (err) linkerr++;
                        linkpromise.resolve(true);
                        linkcount++;
                    });
                });
                delete linksleft[rec.key];
            }
            lookup[rec.key] = rec.id;
        }
        recordcount++;
        Q.all(subpromises).done(function () {
            mypromise.resolve(record);
        });
    });
});

/*var Runtime = graphstore.g.java.import('java.lang.Runtime');
var memcheck = setInterval(function () {
    var usage = process.memoryUsage();
    console.log("Node memory usage: " + (usage.heapUsed / 1048576).toFixed(2) + "/" + (usage.heapTotal / 1048576).toFixed(2));
    console.log("Java memory usage: " + (Runtime.getRuntimeSync().freeMemorySync() / 1048576).toFixed(2) + "/" + (Runtime.getRuntimeSync().totalMemorySync() / 1048576).toFixed(2));
}, 30000);
memcheck.unref();*/
importer.on('commit', function (promise) {
    async.series(linkfuncs, function (err, res) {
        linkfuncs = [ ];
        graphstore.g.commit(function (err, res) {
            promise.resolve(true);
        });
    });
});

importer.on('done', function (rejects) {
    rejects = rejects || [ ];
    if (rejects.length > 0) {
        fs.writeFileSync(options.reject, rejects.join('\n'));
    }
    if (!options.quiet) console.log('Processed ' + mainrecordcount + ' and created ' + recordcount + ' records/' + linkcount + ' links with ' + rejects.length + ' record errors/' + linkerr + ' link errors in ' + process.uptime() + ' seconds');
    process.exit();
});

function addMap(map, promise) {
    var map = map.match(/^([0-9]{3})(.):(.*)$/);
    maps[map[1]] = maps[map[1]] || { };
    maps[map[1]][map[2]] = maps[map[1]][map[2]] || { };
    csv().from.path(map[3]).to.array(function (rows) {
        rows.forEach(function (row, index) {
            if (index > 0) {
                maps[map[1]][map[2]][row[0]] = row[1];
            }
        });
        promise.resolve(true);
    });
}

function valid(object) {
    return typeof object !== 'undefined' && object !== null;
}

function doLink(rec, link, callback) {
    async.waterfall([
        function (cb) {
            cb(null, (link.match ? lookup[JSON.stringify(link.match)] : undefined)
                 || lookup[link.key]);
        },
        function (target, cb) {
            if (valid(target)) {
                cb(null, target);
            } else if (link.match) {
                Record.findOne(link.match, cb);
            } else {
                cb(null, null);
            }
        }, 
        function (target, cb) {
            if (valid(target)) {
                cb(null, target);
            } else {
                Record.findOne({ key: link.key }, cb);
            }
        },
        function (target, cb) {
            if (!valid(target) && typeof link.vivify === 'object') {
                target = new Record(link.vivify);
                target.save(function (err, target) {
                    recordcount++;
                    cb(err, target);
                });
            } else {
                cb(null, target);
            }
        }
    ], function (err, target) {
        if (typeof target !== 'undefined' && target !== null) {
            makeLink(rec, link, target, callback);
        } else if (options.lookup) {
            linksleft[link.key] = linksleft[link.key] || [ ];
            link.source = rec.id;
            linksleft[link.key].push(link);
            callback();
        } else {
            callback();
        }
    });
}

function makeLink(rec, link, target, callback) {
    lookup[link.key] = lookup[link.key] || target.id;
    if (link.match) {
        var matchkey = JSON.stringify(link.match);
        lookup[matchkey] = lookup[matchkey] || lookup[link.key];
    }
    rec.link(link.label, target, link.properties, false, function (err, res) {
        if (err) { linkerr++; console.log(err) };
        linkcount++;
        callback()
    });
}
